### Get all songs
GET http://localhost:8080/api/songs
Content-Type: application/json

### Get all albums
GET http://localhost:8080/api/albums
Content-Type: application/json

### Get album with given id
GET http://localhost:8080/api/albums/1
Content-Type: application/json

###Delete an album with the given id.
DELETE http://localhost:8080/api/albums/1
Content-Type: application/json

### Post a new album
POST http://localhost:8080/api/albums/addAlbum
Content-Type: application/json

{"title": "Barney and Friends", "artistName": "Barney", "imgUrl": "https://static.wikia.nocookie.net/iannielli-legend/images/2/2c/Barney.jpg/revision/latest?cb=20150525032725", "recordLabel": "#"}

### Add a song to an album
POST http://localhost:8080/api/albums/2/addSongToAlbum
Content-Type: application/json

{"id": 1, "title":  "Photograph (Live in ATL)", "linkUrl": "#", "duration": "4:40"}

### get album songs
GET http://localhost:8080/api/albums/1/songs
Content-Type: application/json

### delete an album
DELETE http://localhost:8080/api/albums/2
Content-Type: application/json

### delete a song
DELETE http://localhost:8080/api/songs/4
Content-Type: application/json

### Add an album comment
POST http://localhost:8080/api/albums/1/newComment
Content-Type: application/json

{"username": "Blake", "rating": 1.4, "body": "oh jeez, this guy stinks"}

### Delete a song from an album
DELETE http://localhost:8080/api/songs/13
Content-Type: application/json

### Change a song title
PATCH http://localhost:8080/api/songs/13/editSongTitle

Test
